/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List published entities (directory) */
        get: operations["EntitiesController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Entity detail by slug */
        get: operations["EntitiesController_bySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paginated market feed (newest first) */
        get: operations["NewsController_feed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news/articles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single article with extraction + entity links */
        get: operations["NewsController_byId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clerk webhook receiver — verifies svix signature, upserts User row from user.created/updated/deleted events. */
        post: operations["UsersController_sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current authenticated user profile */
        get: operations["UsersController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a connection request to an entity (Epic 5) */
        post: operations["ConnectionsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/concierge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a concierge request */
        post: operations["ConciergeController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/concierge/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user concierge requests */
        get: operations["ConciergeController_listMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List events (directory) */
        get: operations["EventsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event detail by slug */
        get: operations["EventsController_bySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{slug}/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register for an event. Open to guests by default; if Event.requiresAccount=true the endpoint requires a Clerk session and rejects guests. */
        post: operations["EventsController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List published insights (proxied from Payload, joined with entities) */
        get: operations["InsightsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insights/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Insight detail by slug */
        get: operations["InsightsController_bySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contributors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List public contributors (Payload Authors) */
        get: operations["ContributorsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contributors/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contributor detail by slug */
        get: operations["ContributorsController_bySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gated content download (Story 1.6). Logs userId + contentId + timestamp, returns the file URL. */
        get: operations["DownloadsController_download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/entities/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Entity review queue (filter by publishStatus) */
        get: operations["AdminController_entityQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/entities/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Entity console counters (status totals + needs-attention) */
        get: operations["AdminController_entityCounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/entities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full entity record (id or slug) for detail view */
        get: operations["AdminController_entityDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update analyst-editable fields on an entity profile */
        patch: operations["AdminController_updateEntity"];
        trace?: never;
    };
    "/api/admin/sectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sector list for the edit form dropdown */
        get: operations["AdminController_sectors"];
        put?: never;
        post: operations["AdminController_sectorCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/entities/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark entity CMM_VERIFIED + PUBLISHED, stamp reviewer */
        post: operations["AdminController_approveEntity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/entities/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive entity (low quality / wrong record) */
        post: operations["AdminController_archiveEntity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/news/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** News review queue */
        get: operations["AdminController_newsQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/news/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Header counters: pending / approved / excluded / today / brief */
        get: operations["AdminController_newsCounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/news/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk approve / exclude / toggle brief inclusion */
        post: operations["AdminController_newsBulk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/news/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Distinct sources with tier + counts (filter dropdown) */
        get: operations["AdminController_newsSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/news/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit summary / why-it-matters / brief inclusion / entity links on an article */
        patch: operations["AdminController_updateNews"];
        trace?: never;
    };
    "/api/admin/news/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminController_approveNews"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/news/{id}/exclude": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminController_excludeNews"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/brief/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily brief issue with frozen membership (date=yyyy-mm-dd or "today") */
        get: operations["AdminController_briefByDate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit topSignals on a draft brief */
        patch: operations["AdminController_updateBrief"];
        trace?: never;
    };
    "/api/admin/brief/{date}/articles/{articleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Append an article to the brief (Other tier) */
        post: operations["AdminController_addArticleToBrief"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/brief/{date}/articles/{articleId}/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Remove an article from the draft brief */
        post: operations["AdminController_dropArticleFromBrief"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/brief/{date}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish brief — posts to Slack, freezes membership */
        post: operations["AdminController_publishBrief"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/brief/{date}/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Skip the brief for a date (holiday, no material news) */
        post: operations["AdminController_skipBrief"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clerk-mirrored users with engagement counts */
        get: operations["AdminController_usersList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** User counters: total / investor / issuer / staff / today signups */
        get: operations["AdminController_usersCounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Investor→issuer connection requests */
        get: operations["AdminController_connectionRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/connections/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Connection request counters */
        get: operations["AdminController_connectionCounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/connections/{id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark connection ACKNOWLEDGED (analyst will follow up) */
        post: operations["AdminController_ackConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/connections/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close a connection request (resolved or invalid) */
        post: operations["AdminController_closeConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/connections/{id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reopen a closed/acknowledged connection */
        post: operations["AdminController_reopenConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sources/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pipeline sources joined to recent collection stats */
        get: operations["AdminController_sourceHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/briefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent brief issues across all dates */
        get: operations["AdminController_briefArchive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/concierge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Concierge inbox (PENDING/ACKED/CLOSED) */
        get: operations["AdminController_conciergeList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/concierge/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Concierge counters */
        get: operations["AdminController_conciergeCounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/concierge/{id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminController_conciergeAck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/concierge/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminController_conciergeClose"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/concierge/{id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminController_conciergeReopen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sectors/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full sector list with usage counts */
        get: operations["AdminController_sectorsFull"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sectors/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AdminController_sectorUpdate"];
        trace?: never;
    };
    "/api/admin/sectors/{slug}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminController_sectorDelete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/speakers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List speakers (reusable across events) */
        get: operations["AdminController_speakersList"];
        put?: never;
        /** Create a new speaker */
        post: operations["AdminController_speakerCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/speakers/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a speaker by slug */
        patch: operations["AdminController_speakerUpdate"];
        trace?: never;
    };
    "/api/admin/speakers/{slug}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete a speaker (must have no event links) */
        post: operations["AdminController_speakerDelete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List events with registration + speaker counts */
        get: operations["AdminController_eventsList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/events/{idOrSlug}/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Registration list for an event (id or slug) */
        get: operations["AdminController_eventRegistrations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent pipeline run audit log */
        get: operations["AdminController_runs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single pipeline run with stats + linked brief */
        get: operations["AdminController_run"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        EntityListItemDto: {
            id: string;
            slug: string;
            name: string;
            nameMn?: string;
            entityType: string;
            sectorSlug?: string;
            mseCode?: string;
            logoUrl?: string;
            descriptionPreview?: string;
            isVerified: boolean;
            profileSource: string;
            renderMode?: string;
        };
        EntityListResponseDto: {
            items: components["schemas"]["EntityListItemDto"][];
            total: number;
            limit: number;
            offset: number;
        };
        EntityIdentifierDto: {
            system: string;
            value: string;
        };
        EntityRelationshipDto: {
            relationshipType: string;
            entityId: string;
            name: string;
            slug?: string;
            ownershipPct?: number;
            isControlling: boolean;
        };
        EntityDetailDto: {
            id: string;
            slug: string;
            name: string;
            nameMn?: string;
            entityType: string;
            sectorSlug?: string;
            mseCode?: string;
            logoUrl?: string;
            descriptionPreview?: string;
            isVerified: boolean;
            profileSource: string;
            renderMode?: string;
            websiteUrl?: string;
            country?: string;
            foundingYear?: number;
            employeeCount?: number;
            stockTicker?: string;
            exchange?: string;
            listingLocation?: string;
            description?: string;
            identifiers: components["schemas"]["EntityIdentifierDto"][];
            parents: components["schemas"]["EntityRelationshipDto"][];
            children: components["schemas"]["EntityRelationshipDto"][];
        };
        NewsEntityRefDto: {
            id: string;
            name: string;
            slug?: string;
            matchedOn: string;
            confidence: number;
        };
        NewsFeedItemDto: {
            id: string;
            title: string;
            titleOriginal?: string;
            url: string;
            source: string;
            sourceType: string;
            publishedAt: string;
            summary?: string;
            whyItMatters?: string;
            signalCategory?: string;
            language: string;
            aiTranslated: boolean;
            isIncludedInBrief: boolean;
            entities: components["schemas"]["NewsEntityRefDto"][];
        };
        NewsFeedResponseDto: {
            items: components["schemas"]["NewsFeedItemDto"][];
            /** @description Cursor for next page; null when end reached */
            nextCursor?: Record<string, never>;
        };
        NewsArticleDetailDto: {
            id: string;
            title: string;
            titleOriginal?: string;
            url: string;
            source: string;
            sourceType: string;
            publishedAt: string;
            summary?: string;
            whyItMatters?: string;
            signalCategory?: string;
            language: string;
            aiTranslated: boolean;
            isIncludedInBrief: boolean;
            entities: components["schemas"]["NewsEntityRefDto"][];
            resolvedBody?: string;
            extractedAt?: string;
        };
        WebhookAckDto: {
            ok: boolean;
        };
        UserDto: {
            id: string;
            clerkId: string;
            email: string;
            fullName?: string;
            role?: string;
            country?: string;
            company?: string;
            /** @description Role within CMM staff Clerk Org (admin/analyst/editor) or null */
            cmmOrgRole?: string;
            createdAt: string;
        };
        CreateConnectionDto: {
            /** @description Target entity ID */
            entityId: string;
            message: string;
        };
        ConnectionResponseDto: {
            id: string;
            entityId: string;
            status: string;
            createdAt: string;
        };
        CreateConciergeRequestDto: {
            /** @enum {string} */
            type: "INVESTOR_INTRO" | "COMPANY_INTRO" | "DEAL_FLOW" | "RESEARCH_REQUEST" | "GENERAL";
            /**
             * @default THIS_MONTH
             * @enum {string}
             */
            urgency: "THIS_WEEK" | "THIS_MONTH" | "EXPLORATORY";
            sectorTags?: string[];
            message: string;
        };
        ConciergeRequestResponseDto: {
            id: string;
            type: string;
            urgency: string;
            sectorTags: string[];
            status: string;
            createdAt: string;
        };
        EventListItemDto: {
            id: string;
            slug: string;
            title: string;
            shortName?: string;
            tagline?: string;
            status: string;
            format: string;
            startDate: string;
            endDate?: string;
            location: string;
            city?: string;
            coverImage?: string;
            ticketPrice?: string;
            expectedAttendees?: number;
            registrationCount?: number;
            topics: string[];
        };
        EventListResponseDto: {
            items: components["schemas"]["EventListItemDto"][];
            total: number;
            limit: number;
            offset: number;
        };
        EventSpeakerRefDto: {
            slug: string;
            name: string;
            title?: string;
            company?: string;
            photoUrl?: string;
        };
        EventDetailDto: {
            id: string;
            slug: string;
            title: string;
            shortName?: string;
            tagline?: string;
            status: string;
            format: string;
            startDate: string;
            endDate?: string;
            location: string;
            city?: string;
            coverImage?: string;
            ticketPrice?: string;
            expectedAttendees?: number;
            registrationCount?: number;
            topics: string[];
            description?: string;
            venue?: string;
            registrationDeadline?: string;
            presentingCompanies?: number;
            recapUrl?: string;
            replayUrl?: string;
            sponsors?: {
                [key: string]: unknown;
            };
            agenda?: {
                [key: string]: unknown;
            };
            speakers: components["schemas"]["EventSpeakerRefDto"][];
        };
        CreateEventRegistrationDto: {
            /** @description Required for both guest and logged-in registrations */
            name: string;
            email: string;
            company?: string;
            title?: string;
            country?: string;
            notes?: string;
        };
        EventRegistrationResponseDto: {
            id: string;
            eventId: string;
            status: string;
            createdAt: string;
        };
        InsightAuthorRefDto: {
            slug: string;
            name: string;
            title?: string;
            affiliation?: string;
            photoUrl?: string;
        };
        InsightListItemDto: {
            id: string;
            slug: string;
            title: string;
            contentType: string;
            excerpt?: string;
            coverImageUrl?: string;
            publishedAt?: string;
            author?: components["schemas"]["InsightAuthorRefDto"];
            topics: string[];
            isPremium: boolean;
        };
        InsightListResponseDto: {
            items: components["schemas"]["InsightListItemDto"][];
            total: number;
            page: number;
            limit: number;
            hasNextPage: boolean;
        };
        InsightEntityRefDto: {
            slug: string;
            /** @description Resolved entity name (null when slug not in DB) */
            name?: string;
            logoUrl?: string;
            note?: string;
        };
        InsightDetailDto: {
            id: string;
            slug: string;
            title: string;
            contentType: string;
            excerpt?: string;
            coverImageUrl?: string;
            publishedAt?: string;
            author?: components["schemas"]["InsightAuthorRefDto"];
            topics: string[];
            isPremium: boolean;
            body?: {
                [key: string]: unknown;
            };
            entities: components["schemas"]["InsightEntityRefDto"][];
            pdfAttachmentUrl?: string;
        };
        ContributorListItemDto: {
            slug: string;
            name: string;
            title?: string;
            affiliation?: string;
            photoUrl?: string;
            isActive: boolean;
        };
        ContributorListResponseDto: {
            items: components["schemas"]["ContributorListItemDto"][];
            total: number;
            page: number;
            limit: number;
            hasNextPage: boolean;
        };
        ContributorDetailDto: {
            slug: string;
            name: string;
            title?: string;
            affiliation?: string;
            photoUrl?: string;
            isActive: boolean;
            bio?: string;
            email?: string;
            linkedinUrl?: string;
            twitter?: string;
        };
        DownloadGrantDto: {
            id: string;
            title: string;
            documentType: string;
            /** @description URL to the gated file. Caller redirects or fetches. */
            fileUrl: string;
            loggedAt: string;
        };
        EntityQueueRow: {
            id: string;
            slug: string;
            name: string;
            nameMn?: string;
            entityType: string;
            sectorSlug?: string;
            publishStatus: string;
            profileSource: string;
            completenessScore?: number;
            renderMode?: string;
            lastVerifiedAt?: string;
            lastVerifiedBy?: string;
            createdAt: string;
            updatedAt: string;
            identifierCount: number;
            newsLinkCount: number;
        };
        EntityQueueResponse: {
            items: components["schemas"]["EntityQueueRow"][];
            total: number;
        };
        EntityCountsResponse: {
            pendingReview: number;
            published: number;
            draft: number;
            archived: number;
            needsIdentifier: number;
            staleVerified: number;
        };
        EntityEditDto: {
            nameEn?: string;
            nameMn?: string;
            /** @description Sector slug from sectors table */
            sectorSlug?: string;
            /** @description Analyst-written description (overrides AI prose) */
            descriptionOverride?: string;
            websiteUrl?: string;
            contactEmail?: string;
            contactPhone?: string;
            country?: string;
            foundingYear?: number;
            employeeCount?: number;
            stockTicker?: string;
            exchange?: string;
            /** @enum {string} */
            listingLocation?: "LOCAL" | "FOREIGN";
            marketCap?: number;
            isFeatured?: boolean;
            isVerified?: boolean;
            /** @enum {string} */
            profileTier?: "TIER_1" | "TIER_2" | "TIER_3";
        };
        ActionAck: {
            ok: boolean;
            id: string;
            newStatus: string;
        };
        EntityLinkRow: {
            id: string;
            slug: string;
            nameEn: string;
        };
        NewsQueueRow: {
            id: string;
            title: string;
            url: string;
            source: string;
            /** @description Source tier (1..4) from sources/loader */
            sourceTier?: Record<string, never>;
            publishedAt: string;
            signalScore?: number;
            signalCategory?: string;
            isIncludedInBrief: boolean;
            summary?: string;
            whyItMatters?: string;
            reviewStatus?: string;
            reviewedAt?: string;
            reviewedBy?: string;
            entities: components["schemas"]["EntityLinkRow"][];
            entityNames: string[];
        };
        NewsQueueResponse: {
            items: components["schemas"]["NewsQueueRow"][];
            total: number;
        };
        NewsCountsResponse: {
            pending: number;
            approved: number;
            excluded: number;
            /** @description Articles created today (any status) */
            todayCount: number;
            /** @description Articles flagged as brief candidates */
            briefCandidates: number;
        };
        NewsBulkRequest: {
            ids: string[];
            /** @enum {string} */
            action: "APPROVE" | "EXCLUDE" | "INCLUDE_IN_BRIEF" | "EXCLUDE_FROM_BRIEF";
        };
        NewsBulkResponse: {
            ok: boolean;
            updated: number;
        };
        SourceMetaRow: {
            name: string;
            tier?: Record<string, never>;
            articleCount: number;
            lastPublishedAt?: string;
        };
        NewsEditDto: {
            /** @description Editorial 1-2 sentence summary */
            summary?: string;
            /** @description Why this article matters to MN capital markets */
            whyItMatters?: string;
            /** @description Toggle inclusion in the daily brief */
            isIncludedInBrief?: boolean;
            /** @description Override the signal score (0-1) */
            signalScore?: number;
            /** @description Entity slugs to link (replaces existing links) */
            entitySlugs?: string[];
        };
        BriefArticleRow: {
            id: string;
            title: string;
            url: string;
            source: string;
            publishedAt: string;
            signalScore?: number;
            signalCategory?: string;
            summary?: string;
            whyItMatters?: string;
            reviewStatus?: string;
            tier?: number;
            position: number;
            entityNames: string[];
        };
        BriefIssueResponse: {
            id: string;
            date: string;
            status: string;
            mode: string;
            topSignals: string[];
            publishedAt?: string;
            publishedBy?: string;
            slackTs?: string;
            slackChannel?: string;
            articles: components["schemas"]["BriefArticleRow"][];
        };
        BriefEditDto: {
            /** @description Editorial top-of-letter highlights, one entry per line */
            topSignals?: string[];
        };
        SpeakerEditDto: {
            /** @description Slug (POST only — auto-derived from name if omitted) */
            slug?: string;
            name?: string;
            title?: string;
            company?: string;
            bio?: string;
            photoUrl?: string;
            /** @description Optional FK to Entity.id (link speaker to their company profile) */
            entityId?: string;
        };
        PipelineRunRow: {
            id: string;
            pipelineType: string;
            status: string;
            startedAt: string;
            completedAt?: string;
            cost?: number;
            promptVersion?: string;
        };
        PipelineRunResponse: {
            items: components["schemas"]["PipelineRunRow"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EntitiesController_list: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                entityType?: "PUBLIC_COMPANY" | "PRIVATE_COMPANY" | "PROJECT" | "SERVICE_PROVIDER";
                sectorSlug?: string;
                /** @description Free-text search across nameEn/nameMn/mseCode */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityListResponseDto"];
                };
            };
        };
    };
    EntitiesController_bySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDetailDto"];
                };
            };
        };
    };
    NewsController_feed: {
        parameters: {
            query?: {
                limit?: number;
                /** @description ISO timestamp cursor — returns articles published before this */
                cursor?: string;
                /** @description Filter by entity slug */
                entitySlug?: string;
                /** @description Comma-separated topic tags */
                topics?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsFeedResponseDto"];
                };
            };
        };
    };
    NewsController_byId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsArticleDetailDto"];
                };
            };
        };
    };
    UsersController_sync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookAckDto"];
                };
            };
        };
    };
    UsersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    ConnectionsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConnectionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionResponseDto"];
                };
            };
        };
    };
    ConciergeController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConciergeRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConciergeRequestResponseDto"];
                };
            };
        };
    };
    ConciergeController_listMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConciergeRequestResponseDto"][];
                };
            };
        };
    };
    EventsController_list: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: "UPCOMING" | "REGISTRATION_OPEN" | "SOLD_OUT" | "PAST";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventListResponseDto"];
                };
            };
        };
    };
    EventsController_bySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetailDto"];
                };
            };
        };
    };
    EventsController_register: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventRegistrationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRegistrationResponseDto"];
                };
            };
        };
    };
    InsightsController_list: {
        parameters: {
            query?: {
                limit?: number;
                page?: number;
                /** @description Filter by contentType slug */
                contentType?: string;
                /** @description Filter by topic-tag slug */
                topic?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightListResponseDto"];
                };
            };
        };
    };
    InsightsController_bySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightDetailDto"];
                };
            };
        };
    };
    ContributorsController_list: {
        parameters: {
            query?: {
                limit?: number;
                page?: number;
                /** @description Only show isActive=true (default) */
                activeOnly?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContributorListResponseDto"];
                };
            };
        };
    };
    ContributorsController_bySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContributorDetailDto"];
                };
            };
        };
    };
    DownloadsController_download: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadGrantDto"];
                };
            };
        };
    };
    AdminController_entityQueue: {
        parameters: {
            query?: {
                status?: "PENDING_REVIEW" | "DRAFT" | "PUBLISHED" | "ARCHIVED" | "ALL";
                limit?: number;
                offset?: number;
                sector?: string;
                profileSource?: string;
                minCompleteness?: number;
                maxCompleteness?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityQueueResponse"];
                };
            };
        };
    };
    AdminController_entityCounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityCountsResponse"];
                };
            };
        };
    };
    AdminController_entityDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_updateEntity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityEditDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionAck"];
                };
            };
        };
    };
    AdminController_sectors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_sectorCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionAck"];
                };
            };
        };
    };
    AdminController_approveEntity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionAck"];
                };
            };
        };
    };
    AdminController_archiveEntity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionAck"];
                };
            };
        };
    };
    AdminController_newsQueue: {
        parameters: {
            query?: {
                reviewStatus?: string;
                limit?: number;
                offset?: number;
                /** @description Restrict to brief candidates only */
                inBriefOnly?: boolean;
                /** @description Filter by source name (exact match) */
                source?: string;
                /** @description Filter by source tier (1..4) */
                tier?: number;
                /** @description Min signalScore [0..1] */
                minScore?: number;
                /** @description Articles with at least one entity link */
                hasEntity?: boolean;
                /** @description Title contains (case-insensitive) */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsQueueResponse"];
                };
            };
        };
    };
    AdminController_newsCounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsCountsResponse"];
                };
            };
        };
    };
    AdminController_newsBulk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewsBulkRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsBulkResponse"];
                };
            };
        };
    };
    AdminController_newsSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceMetaRow"][];
                };
            };
        };
    };
    AdminController_updateNews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewsEditDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionAck"];
                };
            };
        };
    };
    AdminController_approveNews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionAck"];
                };
            };
        };
    };
    AdminController_excludeNews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionAck"];
                };
            };
        };
    };
    AdminController_briefByDate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefIssueResponse"];
                };
            };
        };
    };
    AdminController_updateBrief: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BriefEditDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionAck"];
                };
            };
        };
    };
    AdminController_addArticleToBrief: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
                articleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionAck"];
                };
            };
        };
    };
    AdminController_dropArticleFromBrief: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
                articleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionAck"];
                };
            };
        };
    };
    AdminController_publishBrief: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionAck"];
                };
            };
        };
    };
    AdminController_skipBrief: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionAck"];
                };
            };
        };
    };
    AdminController_usersList: {
        parameters: {
            query: {
                role: string;
                cmmOrgRole: string;
                search: string;
                limit: number;
                offset: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_usersCounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_connectionRequests: {
        parameters: {
            query: {
                status: string;
                limit: number;
                offset: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_connectionCounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_ackConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionAck"];
                };
            };
        };
    };
    AdminController_closeConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionAck"];
                };
            };
        };
    };
    AdminController_reopenConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionAck"];
                };
            };
        };
    };
    AdminController_sourceHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_briefArchive: {
        parameters: {
            query: {
                limit: number;
                offset: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_conciergeList: {
        parameters: {
            query: {
                status: string;
                type: string;
                urgency: string;
                limit: number;
                offset: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_conciergeCounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_conciergeAck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionAck"];
                };
            };
        };
    };
    AdminController_conciergeClose: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionAck"];
                };
            };
        };
    };
    AdminController_conciergeReopen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionAck"];
                };
            };
        };
    };
    AdminController_sectorsFull: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_sectorUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionAck"];
                };
            };
        };
    };
    AdminController_sectorDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionAck"];
                };
            };
        };
    };
    AdminController_speakersList: {
        parameters: {
            query: {
                search: string;
                entityId: string;
                limit: number;
                offset: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_speakerCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeakerEditDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionAck"];
                };
            };
        };
    };
    AdminController_speakerUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeakerEditDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionAck"];
                };
            };
        };
    };
    AdminController_speakerDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionAck"];
                };
            };
        };
    };
    AdminController_eventsList: {
        parameters: {
            query: {
                status: string;
                search: string;
                limit: number;
                offset: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_eventRegistrations: {
        parameters: {
            query: {
                status: string;
                limit: number;
                offset: number;
            };
            header?: never;
            path: {
                idOrSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_runs: {
        parameters: {
            query: {
                limit: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRunResponse"];
                };
            };
        };
    };
    AdminController_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
